// TermsPage.tsx — Terms of Service (public, no login required).

import { Link } from 'react-router-dom';
import { Brain, ArrowLeft } from 'lucide-react';
import { APP_NAME, APP_SUPPORT_EMAIL } from '@/constants';

export function TermsPage() {
  return (
    <div className="min-h-screen bg-[#FAFBFC]">
      <nav className="flex items-center justify-between px-6 lg:px-12 py-4 bg-white/80 backdrop-blur-xl border-b border-slate-200/60 sticky top-0 z-50">
        <Link to="/" className="flex items-center gap-2.5">
          <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-gradient-to-br from-[#3B82F6] to-[#06B6D4]">
            <Brain className="h-5 w-5 text-white" />
          </div>
          <span className="text-lg font-bold text-dark-text tracking-tight">{APP_NAME}</span>
        </Link>
        <Link to="/demo" className="flex items-center gap-1.5 text-sm text-slate-500 hover:text-electric transition-colors">
          <ArrowLeft className="h-4 w-4" /> Back
        </Link>
      </nav>

      <div className="max-w-3xl mx-auto px-6 py-12">
        <h1 className="text-3xl font-extrabold text-dark-text tracking-tight mb-2">Terms of Service</h1>
        <p className="text-sm text-slate-400 mb-10">Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>

        <div className="prose prose-slate prose-sm max-w-none space-y-6 text-slate-600 leading-relaxed">
          <section>
            <h2 className="text-lg font-bold text-dark-text mt-8 mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using {APP_NAME} ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-dark-text mt-8 mb-3">2. Description of Service</h2>
            <p>{APP_NAME} is a cloud-based dental treatment planning platform that provides AI-powered tooth segmentation, treatment staging, manufacturing management, and related dental laboratory services. The Service is intended for use by licensed dental professionals and authorized dental laboratory personnel.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-dark-text mt-8 mb-3">3. Account Registration</h2>
            <p>To use the Service, you must create an account and provide accurate, complete information. You are responsible for maintaining the confidentiality of your account credentials. You must be at least 18 years old to use the Service.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-dark-text mt-8 mb-3">4. Subscription & Billing</h2>
            <p>The Service offers various subscription plans. By subscribing, you agree to pay the applicable fees. Subscriptions renew automatically unless cancelled. Refunds are handled on a case-by-case basis. Prices may change with 30 days' notice.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-dark-text mt-8 mb-3">5. User Data & Patient Information</h2>
            <p>You retain ownership of all patient data and files uploaded to the Service. We process this data solely to provide the Service. You are responsible for obtaining patient consent for digital treatment planning. We do not sell or share patient data with third parties.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-dark-text mt-8 mb-3">6. AI-Generated Results</h2>
            <p>The AI segmentation and treatment plans generated by the Service are intended as clinical decision support tools. They do not replace professional dental judgment. The treating dentist is solely responsible for all clinical decisions and patient outcomes.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-dark-text mt-8 mb-3">7. Acceptable Use</h2>
            <p>You agree not to: (a) use the Service for unlawful purposes; (b) attempt to gain unauthorized access; (c) upload malicious content; (d) reverse-engineer the AI models; (e) resell the Service without authorization.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-dark-text mt-8 mb-3">8. Intellectual Property</h2>
            <p>The Service, including its AI models, software, and design, is the property of {APP_NAME}. Your uploaded data remains your property. We may use anonymized, aggregated data to improve the AI models.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-dark-text mt-8 mb-3">9. Limitation of Liability</h2>
            <p>{APP_NAME} provides the Service "as is" without warranty of any kind. We are not liable for any indirect, incidental, or consequential damages arising from use of the Service. Our total liability shall not exceed the amount paid by you in the 12 months preceding the claim.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-dark-text mt-8 mb-3">10. Termination</h2>
            <p>Either party may terminate the account at any time. Upon termination, you may request export of your data within 30 days. After 30 days, your data may be permanently deleted.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-dark-text mt-8 mb-3">11. Changes to Terms</h2>
            <p>We may update these Terms from time to time. We will notify you of significant changes via email or in-app notification. Continued use after changes constitutes acceptance.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-dark-text mt-8 mb-3">12. Contact</h2>
            <p>For questions about these Terms, contact us at <a href={`mailto:${APP_SUPPORT_EMAIL}`} className="text-electric hover:underline">{APP_SUPPORT_EMAIL}</a>.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
